# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/amanshenoy/Desktop/projects/github/ray-tracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/amanshenoy/Desktop/projects/github/ray-tracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amanshenoy/Desktop/projects/github/ray-tracer/CMakeFiles /home/amanshenoy/Desktop/projects/github/ray-tracer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amanshenoy/Desktop/projects/github/ray-tracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named path-tracer

# Build rule for target.
path-tracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 path-tracer
.PHONY : path-tracer

# fast build rule for target.
path-tracer/fast:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/build
.PHONY : path-tracer/fast

src/core/background.o: src/core/background.cpp.o

.PHONY : src/core/background.o

# target to build an object file
src/core/background.cpp.o:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/core/background.cpp.o
.PHONY : src/core/background.cpp.o

src/core/background.i: src/core/background.cpp.i

.PHONY : src/core/background.i

# target to preprocess a source file
src/core/background.cpp.i:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/core/background.cpp.i
.PHONY : src/core/background.cpp.i

src/core/background.s: src/core/background.cpp.s

.PHONY : src/core/background.s

# target to generate assembly for a file
src/core/background.cpp.s:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/core/background.cpp.s
.PHONY : src/core/background.cpp.s

src/core/camera.o: src/core/camera.cpp.o

.PHONY : src/core/camera.o

# target to build an object file
src/core/camera.cpp.o:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/core/camera.cpp.o
.PHONY : src/core/camera.cpp.o

src/core/camera.i: src/core/camera.cpp.i

.PHONY : src/core/camera.i

# target to preprocess a source file
src/core/camera.cpp.i:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/core/camera.cpp.i
.PHONY : src/core/camera.cpp.i

src/core/camera.s: src/core/camera.cpp.s

.PHONY : src/core/camera.s

# target to generate assembly for a file
src/core/camera.cpp.s:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/core/camera.cpp.s
.PHONY : src/core/camera.cpp.s

src/core/materials.o: src/core/materials.cpp.o

.PHONY : src/core/materials.o

# target to build an object file
src/core/materials.cpp.o:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/core/materials.cpp.o
.PHONY : src/core/materials.cpp.o

src/core/materials.i: src/core/materials.cpp.i

.PHONY : src/core/materials.i

# target to preprocess a source file
src/core/materials.cpp.i:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/core/materials.cpp.i
.PHONY : src/core/materials.cpp.i

src/core/materials.s: src/core/materials.cpp.s

.PHONY : src/core/materials.s

# target to generate assembly for a file
src/core/materials.cpp.s:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/core/materials.cpp.s
.PHONY : src/core/materials.cpp.s

src/core/objects.o: src/core/objects.cpp.o

.PHONY : src/core/objects.o

# target to build an object file
src/core/objects.cpp.o:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/core/objects.cpp.o
.PHONY : src/core/objects.cpp.o

src/core/objects.i: src/core/objects.cpp.i

.PHONY : src/core/objects.i

# target to preprocess a source file
src/core/objects.cpp.i:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/core/objects.cpp.i
.PHONY : src/core/objects.cpp.i

src/core/objects.s: src/core/objects.cpp.s

.PHONY : src/core/objects.s

# target to generate assembly for a file
src/core/objects.cpp.s:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/core/objects.cpp.s
.PHONY : src/core/objects.cpp.s

src/core/ray.o: src/core/ray.cpp.o

.PHONY : src/core/ray.o

# target to build an object file
src/core/ray.cpp.o:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/core/ray.cpp.o
.PHONY : src/core/ray.cpp.o

src/core/ray.i: src/core/ray.cpp.i

.PHONY : src/core/ray.i

# target to preprocess a source file
src/core/ray.cpp.i:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/core/ray.cpp.i
.PHONY : src/core/ray.cpp.i

src/core/ray.s: src/core/ray.cpp.s

.PHONY : src/core/ray.s

# target to generate assembly for a file
src/core/ray.cpp.s:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/core/ray.cpp.s
.PHONY : src/core/ray.cpp.s

src/dependancies/stb_image.o: src/dependancies/stb_image.cpp.o

.PHONY : src/dependancies/stb_image.o

# target to build an object file
src/dependancies/stb_image.cpp.o:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/dependancies/stb_image.cpp.o
.PHONY : src/dependancies/stb_image.cpp.o

src/dependancies/stb_image.i: src/dependancies/stb_image.cpp.i

.PHONY : src/dependancies/stb_image.i

# target to preprocess a source file
src/dependancies/stb_image.cpp.i:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/dependancies/stb_image.cpp.i
.PHONY : src/dependancies/stb_image.cpp.i

src/dependancies/stb_image.s: src/dependancies/stb_image.cpp.s

.PHONY : src/dependancies/stb_image.s

# target to generate assembly for a file
src/dependancies/stb_image.cpp.s:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/dependancies/stb_image.cpp.s
.PHONY : src/dependancies/stb_image.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/optim/aabb.o: src/optim/aabb.cpp.o

.PHONY : src/optim/aabb.o

# target to build an object file
src/optim/aabb.cpp.o:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/optim/aabb.cpp.o
.PHONY : src/optim/aabb.cpp.o

src/optim/aabb.i: src/optim/aabb.cpp.i

.PHONY : src/optim/aabb.i

# target to preprocess a source file
src/optim/aabb.cpp.i:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/optim/aabb.cpp.i
.PHONY : src/optim/aabb.cpp.i

src/optim/aabb.s: src/optim/aabb.cpp.s

.PHONY : src/optim/aabb.s

# target to generate assembly for a file
src/optim/aabb.cpp.s:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/optim/aabb.cpp.s
.PHONY : src/optim/aabb.cpp.s

src/optim/bvh.o: src/optim/bvh.cpp.o

.PHONY : src/optim/bvh.o

# target to build an object file
src/optim/bvh.cpp.o:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/optim/bvh.cpp.o
.PHONY : src/optim/bvh.cpp.o

src/optim/bvh.i: src/optim/bvh.cpp.i

.PHONY : src/optim/bvh.i

# target to preprocess a source file
src/optim/bvh.cpp.i:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/optim/bvh.cpp.i
.PHONY : src/optim/bvh.cpp.i

src/optim/bvh.s: src/optim/bvh.cpp.s

.PHONY : src/optim/bvh.s

# target to generate assembly for a file
src/optim/bvh.cpp.s:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/optim/bvh.cpp.s
.PHONY : src/optim/bvh.cpp.s

src/shaders/bsdf.o: src/shaders/bsdf.cpp.o

.PHONY : src/shaders/bsdf.o

# target to build an object file
src/shaders/bsdf.cpp.o:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/shaders/bsdf.cpp.o
.PHONY : src/shaders/bsdf.cpp.o

src/shaders/bsdf.i: src/shaders/bsdf.cpp.i

.PHONY : src/shaders/bsdf.i

# target to preprocess a source file
src/shaders/bsdf.cpp.i:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/shaders/bsdf.cpp.i
.PHONY : src/shaders/bsdf.cpp.i

src/shaders/bsdf.s: src/shaders/bsdf.cpp.s

.PHONY : src/shaders/bsdf.s

# target to generate assembly for a file
src/shaders/bsdf.cpp.s:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/shaders/bsdf.cpp.s
.PHONY : src/shaders/bsdf.cpp.s

src/utils/pdf.o: src/utils/pdf.cpp.o

.PHONY : src/utils/pdf.o

# target to build an object file
src/utils/pdf.cpp.o:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/utils/pdf.cpp.o
.PHONY : src/utils/pdf.cpp.o

src/utils/pdf.i: src/utils/pdf.cpp.i

.PHONY : src/utils/pdf.i

# target to preprocess a source file
src/utils/pdf.cpp.i:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/utils/pdf.cpp.i
.PHONY : src/utils/pdf.cpp.i

src/utils/pdf.s: src/utils/pdf.cpp.s

.PHONY : src/utils/pdf.s

# target to generate assembly for a file
src/utils/pdf.cpp.s:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/utils/pdf.cpp.s
.PHONY : src/utils/pdf.cpp.s

src/utils/utils.o: src/utils/utils.cpp.o

.PHONY : src/utils/utils.o

# target to build an object file
src/utils/utils.cpp.o:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/utils/utils.cpp.o
.PHONY : src/utils/utils.cpp.o

src/utils/utils.i: src/utils/utils.cpp.i

.PHONY : src/utils/utils.i

# target to preprocess a source file
src/utils/utils.cpp.i:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/utils/utils.cpp.i
.PHONY : src/utils/utils.cpp.i

src/utils/utils.s: src/utils/utils.cpp.s

.PHONY : src/utils/utils.s

# target to generate assembly for a file
src/utils/utils.cpp.s:
	$(MAKE) -f CMakeFiles/path-tracer.dir/build.make CMakeFiles/path-tracer.dir/src/utils/utils.cpp.s
.PHONY : src/utils/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... path-tracer"
	@echo "... src/core/background.o"
	@echo "... src/core/background.i"
	@echo "... src/core/background.s"
	@echo "... src/core/camera.o"
	@echo "... src/core/camera.i"
	@echo "... src/core/camera.s"
	@echo "... src/core/materials.o"
	@echo "... src/core/materials.i"
	@echo "... src/core/materials.s"
	@echo "... src/core/objects.o"
	@echo "... src/core/objects.i"
	@echo "... src/core/objects.s"
	@echo "... src/core/ray.o"
	@echo "... src/core/ray.i"
	@echo "... src/core/ray.s"
	@echo "... src/dependancies/stb_image.o"
	@echo "... src/dependancies/stb_image.i"
	@echo "... src/dependancies/stb_image.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/optim/aabb.o"
	@echo "... src/optim/aabb.i"
	@echo "... src/optim/aabb.s"
	@echo "... src/optim/bvh.o"
	@echo "... src/optim/bvh.i"
	@echo "... src/optim/bvh.s"
	@echo "... src/shaders/bsdf.o"
	@echo "... src/shaders/bsdf.i"
	@echo "... src/shaders/bsdf.s"
	@echo "... src/utils/pdf.o"
	@echo "... src/utils/pdf.i"
	@echo "... src/utils/pdf.s"
	@echo "... src/utils/utils.o"
	@echo "... src/utils/utils.i"
	@echo "... src/utils/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

